<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/6
 * Time: 15:22
 */
namespace app\index\controller;
use think\Controller;
class Base extends Controller{
    public function _initialize()
    {
        $this->right();
        $cate = db('cate')->select();
        $tag = db('tags')
//            ->order('click desc')
            ->limit(7)->select();
        //热门点击
        $this->assign('tag',$tag);
        $this->assign('cate',$cate);
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function right(){
        $hc = db('article')->field('id,title')->order('click desc')->limit(4)->select();
        //热门推荐
        $ht = db('article')->field('id,title')->where(['state'=>1])->order('click desc')->limit(4)->select();
        $this->assign('hc',$hc);
        $this->assign('ht',$ht);
    }
}